### PR TITLE
fix: use `health` instead of `status` in config details

### LINKED ISSUE #1883: Use `health` instead of `status` in config details
An unhealthy config is shown as green.

image

We have added a new `health` column with possible values
- healthy
- unhealthy
- warn
- unknown
- and possibly null

Also we might need to have a display for `ready` as well @moshloop

### PR DESCRIPTION
**Pull request by mainawycliffe**
Fixes #1883

### CODE REVIEW

**Comment by adityathebe** [comment]
@moshloop do we want to show the readiness as well?

**Comment by adityathebe** [comment]
@mainawycliffe doesn't look like we're using `health` in the main table?

image
image

**Comment by mainawycliffe** [comment]
@adityathebe the health field is missing from the configs view

**Comment by adityathebe** [comment]
> @adityathebe the health field is missing from the configs view

added it

**Comment by mainawycliffe** [comment]
@adityathebe Thanks, should be good now

**Comment by moshloop** [comment]
@mainawycliffe The `health` is for the dot, while the `status` is for the text and `description` is for the text below

**Comment by moshloop** [comment]
@mainawycliffe - I am expected this to be "Failed", not unhealthy - This applies to the table as well
Screenshot 2024-04-28 at 16 36 37

https://deploy-preview-1890--goofy-euclid-75956c.netlify.app/catalog/822d8e05-c7c4-4822-b3c3-1a3e93b8e4ce

**Comment by moshloop** [comment]
> @mainawycliffe doesn't look like we're using `health` in the main table?
> 
> image image

In that case the dot should be red, and the status should remain PodCrashloopbackoff

**Pull request merged**
