### PR TITLE
feat(logs): add empty state and sort components in asc order

### LINKED ISSUE #419: Logs - Add empty state + add sorting
- [ ] On https://incident-commander.canary.lab.flanksource.com/logs - add an empty state asking to select a component to view logs
- [ ] Sort the components by name in the drop down

### PR DESCRIPTION
**Pull request by PulkitBanta**
Fixes #419 

## Screenshots
Screenshot 2022-09-09 at 5 11 26 PM

### CODE REVIEW

**Comment by moshloop** [comment]
@PulkitBanta looks good from a functional perspective,   Could you maybe try and make it look a little better
- Search for UI/UX designs for empty states
- The dropdown looks a little weird in the corner like that - maybe it should be centered, and the page also gets a title?

**Comment by PulkitBanta** [comment]
@moshloop I have made the requested changes to
* center the dropdown for component selection
* update empty screen
* add title for the screen

**Comment by ciju** [comment]
lgtm. could be rebased and merged?

**Comment by PulkitBanta** [comment]
@ciju there was a merge conflict in `logs-page.js` and has been fixed, it should be ready to merge now

**Comment by moshloop** [comment]
@PulkitBanta can you remove the image (we will find something more subtle at a later point) and then also change the placeholder from Select to Select Component?

**Comment by PulkitBanta** [comment]
@moshloop I have made the requested changes and this PR can be squash and merged.

**Pull request merged**
