### PR TITLE
1353-components-playbooks

### LINKED ISSUE #1353: Components -> Playbooks
1) Add a menu item on component detail sidebar, that lists available playbooks to run, on click on a playbook popup a dialog to enter parameters and then submit playbook run

### PR DESCRIPTION
**Pull request by mainawycliffe**
Build on top of the #1357 PR

Closes #1353

### CODE REVIEW

**Comment by mainawycliffe** [comment]
@moshloop this is good to go as well

**Comment by moshloop** [comment]
@mainawycliffe  Can we change the button into menu button called Playbooks - which then loads the list of playbooks that can be run from /playbooks/list - https://github.com/flanksource/incident-commander/blob/main/playbook/controllers.go#L167

**Comment by mainawycliffe** [comment]
@moshloop got it

**Comment by mainawycliffe** [comment]
@moshloop is something like this what you had in mind?

image

**Pull request merged**
