### PR TITLE
fix: close health check modal on clicking esc button

### LINKED ISSUE #810: Health check modal - Esc does not close the window

### PR DESCRIPTION
**Pull request by Prashanth-Nelli**
Closes #810

### CODE REVIEW

**Comment by moshloop** [comment]
@Prashanth-Nelli this still has an empty dialog box shown,just before closing

**Comment by Prashanth-Nelli** [comment]
@moshloop fixed it.

**Comment by moshloop** [comment]
@Prashanth-Nelli have a look at https://www.loom.com/share/9c718a2353284ef8bbd9222e77a5ae44 - there is something funny happening

**Comment by Prashanth-Nelli** [comment]
Let me check

**Comment by moshloop** [comment]
@Prashanth-Nelli - I am getting an error page when clicking on check item

**Comment by Prashanth-Nelli** [comment]
@moshloop fixed the error.

**Comment by moshloop** [comment]
@Prashanth-Nelli this still does not appear to be working - Can we not just switch to use /api/db/check_statuses directly ?

**Comment by moshloop** [comment]
- When closing the dialog, I can see the time range change to 15 minutes just before closing
- Can we send the date up in RFC format, 
- The status history should also update with the time range, and it should probably be paginated as well

**Pull request merged**
