### PR TITLE
feat: show reverse config relationships in the database

### LINKED ISSUE #566: Show reverse config relationships in the database
Config items can be linked via both config_id and related_id, so we should query both the fields when showing the relationships.

Sample config: https://incident-commander.canary.lab.flanksource.com/configs/01840db0-93eb-7bc7-d10a-6aebea743fa9

image

### PR DESCRIPTION
**Pull request by mainawycliffe**
Closes #566

### CODE REVIEW

**Comment by yashmehrotra** [comment]
@mainawycliffe Small bug: The current config item is showing itself too, we need to exclude that: https://deploy-preview-567--goofy-euclid-75956c.netlify.app/configs/01840db0-93eb-7bc7-d10a-6aebea743fa9

image

Also, the cluster should show instances but its not showing any
image

**Comment by mainawycliffe** [comment]
@yashmehrotra ah, let me resolve that, I noticed something wierd but was unable to pin it down as config dB went down last night. 

Is there something I can do when this happens?

**Comment by yashmehrotra** [comment]
> Is there something I can do when this happens?
This is due to postgrest, it won't happen now on config-db

**Comment by mainawycliffe** [comment]
> Also, the cluster should show instances but its not showing any

@yashmehrotra can you elaborate on this point?

**Comment by yashmehrotra** [comment]
@mainawycliffe https://deploy-preview-567--goofy-euclid-75956c.netlify.app/configs/0182c52e-0153-a831-7c68-ba5c2912e0a8 This is a EKS Cluster config item, in this it shows related ec2 nodes. But if you click on any of the nodes, they do not show the cluster as a related config, we need to show the cluster as a config item there as well

**Comment by moshloop** [comment]
@mainawycliffe Please check the errors

**Pull request merged**
