### PR TITLE
FLNK-879 - Form - Health - DNS

### LINKED ISSUE #879: Form - Health - DNS

### PR DESCRIPTION
**Pull request by gitstart-flanksource**
Closes #879

### CODE REVIEW

**Comment by mainawycliffe** [comment]
@gitstart-flanksource The specs for the health DNS form can be found here https://docs.flanksource.com/canary-checker/reference/dns/, with needed fields, second, the layout should be quite similar to other existing forms:

image

**Comment by gitstart-flanksource** [comment]
Thanks for the feedback @mainawycliffe, we are on it

**Comment by gitstart-flanksource** [comment]
Your feedback has been implemented @mainawycliffe

**Comment by mainawycliffe** [comment]
@gitstart-flanksource build is failing, checkout why

**Comment by gitstart-flanksource** [comment]
> @gitstart-flanksource build is failing, checkout why

I'll look into it

**Comment by gitstart-flanksource** [comment]
> @gitstart-flanksource build is failing, checkout why

Hi @mainawycliffe, after looking through the CI logs, it looks like the problem is a result of failure to install dependencies. Can you try rerunning it to see if it is a recurring problem?

**Comment by mainawycliffe** [comment]
@gitstart-flanksource rebase against main, that should re-run the checks

**Comment by gitstart-flanksource** [comment]
Alright @mainawycliffe, looks like they are passing now.

**Comment by moshloop** [comment]
Does not save

**Pull request closed without merging**
