### PR TITLE
feat: add incident type field changes

### PR DESCRIPTION
**Pull request by Prashanth-Nelli**

### CODE REVIEW

**Comment by moshloop** [comment]
@Prashanth-Nelli I the type dropdown seems to have disappeared.  

Can we also add a column to the table, and reorder the columns Type, Severity, Name

**Comment by Prashanth-Nelli** [comment]
> https://deploy-preview-382--goofy-euclid-75956c.netlify.app/
I have added the type filter in the header.

Screenshot 2022-08-19 at 12 51 56 PM

**Comment by moshloop** [comment]
@Prashanth-Nelli can we update the create an incident dialog as well - and make incident-type required and default to availability

**Comment by moshloop** [comment]
And also fix the width of the type and severity columns

**Comment by moshloop** [comment]
@Prashanth-Nelli just need to update the Attach to evidence dialog

**Pull request merged**
