### PR TITLE
FLNK-1114 - Analysis icon heights are not consistent

### LINKED ISSUE #1114: Analysis icon heights are not consistent
Screenshot 2023-05-10 at 14 05 46

### PR DESCRIPTION
**Pull request by gitstart-flanksource**
closes #1114

The Analysis icons in appearance are different in size despite having the same size value. In that regard, some of the sizes had to be adjusted so the icons could have the same size in appearance.

[Loom Video](https://www.loom.com/share/6e4ebc2a4e28443c9d205feb3f7ccc6c)

### CODE REVIEW

**Comment by gitstart-flanksource** [comment]
@moshloop this PR is ready for review

**Comment by moshloop** [comment]
@gitstart-flanksource  I think this change needs to be on the svg files directly

**Comment by gitstart-flanksource** [comment]
Thanks for the feedback @moshloop, we are on it.

**Comment by gitstart** [comment]
@moshloop Apologies for the delay in updating this PR. The Analysis icons are imported from `react-icons`, not sure we can make the changes on the svg files directly.

**Comment by gitstart-flanksource** [comment]
@moshloop Apologies for the delay in updating this PR. The Analysis icons are imported from react-icons, not sure we can make the changes on the svg files directly.

**Pull request closed without merging**
