### PR TITLE
fix: fix sorting and paging not working on config changes

### PR DESCRIPTION
**Pull request by mainawycliffe**

### CODE REVIEW

**Comment by moshloop** [comment]
@mainawycliffe it doesn't look like the page size is included in the first request

**Comment by moshloop** [comment]
@mainawycliffe can we default the sort on changes to be by last seen ?

**Comment by mainawycliffe** [comment]
@moshloop the backend only allows name, change_type, summary, source, created_at, count for sorting

**Comment by moshloop** [comment]
@mainawycliffe - created_at is last seen - before it was sorted by most recent, and now its unsorted which doesn't make sense when looking at history

**Pull request merged**
