### PR TITLE
fix: url rewrites in local setup

### PR DESCRIPTION
**Pull request by adityathebe**

### CODE REVIEW

**Comment by mainawycliffe** [comment]
@adityathebe this will break the UI for anyone using it with incident-commander proxy (https://incident-commander.canary.lab.flanksource.com/). Since the proxy is a nextjs server, it expects API to be present, for it to route properly. May be add another flag for situations where one is using a backend that's on localhost or something like that.

```env
# env.local
SKIP_PREFLIGHT_CHECK=true
PORT=3004
# ORY_KRATOS_URL=http://kratos.canary.lab.flanksource.com/
# NEXT_PUBLIC_APP_DEPLOYMENT=CANARY_CHECKER
NEXT_PUBLIC_WITHOUT_SESSION=false
BACKEND_URL=https://incident-commander.canary.lab.flanksource.com/
ENV=localhost
REACT_EDITOR=code
```

**Review by mainawycliffe — APPROVED** [review]
LGTM, we need to be careful merging this in, as it will break netlify previews until everyone rebases, let me figure out the least disruptive way of doing it.

**Comment by mainawycliffe** [comment]
@adityathebe can we also squash the commits and rebase.

**Comment by adityathebe** [comment]
> @adityathebe can we also squash the commits and rebase.

Should be good @mainawycliffe

**Comment by adityathebe** [comment]
@mainawycliffe Can we merge this?

**Comment by mainawycliffe** [comment]
@adityathebe Yeah, I have been meaning to find some time to merge it. Changes to the next.config.js can be a little tricky to merge in and test and will affect all PR previews until they rebuild.

**Comment by moshloop** [comment]
@mainawycliffe is this mergable ?

**Comment by mainawycliffe** [comment]
@moshloop Yeah, we just need to update the Netlfify Backend URL after merging it and re-build the PRs for new changes to kick in.

**Pull request closed without merging**
