### PR TITLE
feat: add responder flow changes

### PR DESCRIPTION
**Pull request by Prashanth-Nelli**

### CODE REVIEW

**Comment by moshloop** [comment]
Can we do something more like this (with icons replacing the radios) on a wider dialog 

Screenshot 2022-06-29 at 10 13 20

And then maybe steps (Responder Type -> Details)

Screenshot 2022-06-29 at 10 16 00

Source is on the tailwindui.com website

**Comment by moshloop** [comment]
Looking better, still need to:

* Display responder type / title rather than person who created responder, 
* Add remove button
* Move button inline
* remove scrolling

**Comment by moshloop** [comment]
* I can't seem to click on the Save button? and/or on click the responder doesn't get added to the list I need to refresh it
* In the responder list it should be icon {To|Title|etcc} not the responder type
* The add responder link should be styled as a link
* The styling doesn't seem to fit with the rest of the panel

**Comment by Prashanth-Nelli** [comment]
> * I can't seem to click on the Save button? and/or on click the responder doesn't get added to the list I need to refresh it
> * In the responder list it should be icon {To|Title|etcc} not the responder type
> * The add responder link should be styled as a link
> * The styling doesn't seem to fit with the rest of the panel

I am using the below mapping let me know if you need any changes

> const getResponderTitle = (properties) => {
    if (properties.responderType === "Email") {
      return properties.to;
    } else if (properties.responderType === "AWS AMS Service Request") {
      return properties.category;
    } else if (properties.responderType === "AWS Support") {
      return properties.category;
    } else if (properties.responderType === "ServiceNow") {
      return properties.category;
    } else if (properties.responderType === "CA") {
      return properties.category;
    } else if (properties.responderType === "Redhat") {
      return properties.product;
    } else if (properties.responderType === "Oracle") {
      return properties.product;
    } else if (properties.responderType === "Microsoft") {
      return properties.product;
    } else if (properties.responderType === "VMWare") {
      return properties.product;
    } else if (properties.responderType === "Person") {
      return properties.person;
    } else if (properties.responderType === "Jira") {
      return properties.project;
    }
  };
  
The last point I am not sure what is expected in terms of styling changes. Remaining are handled.

**Comment by moshloop** [comment]
1. The responder type tile should not be on a new line
Screenshot 2022-07-08 at 10 49 58
2. The icons should not be rounded or have background colors:
Screenshot 2022-07-08 at 10 50 13
3. The "row" should have a light grey, small rounded border hover effect
4. Reduce the vertical gap
5. Add Responder link should not have already visited clicked style.
6. The popup is too wide, The steps should be at the top, not bottom
7. Show human date (3:14am yesterday, 10:20pm and date in locale format)  - maybe we should create a helper function for this to use all over
8.  Between the created and acknowledge show a duration "badge" and between acknowledge and sign off (rename it to Resolved) add a duration badge or a clock and again from resolved to Close (will add in the backend api)

**Pull request merged**
