### PR TITLE
1351-dropdowns-fixed-height

### LINKED ISSUE #1351: All dropdowns should have a fixed height
e.g. 
Screenshot 2023-08-30 at 11 48 05

The icons should shrink/grow to fit that height

### PR DESCRIPTION
**Pull request by mainawycliffe**
Closes #1351

### CODE REVIEW

**Comment by moshloop** [comment]
@mainawycliffe  

Dashboard filters are not consistent

Screenshot 2023-09-19 at 11 52 09

Also on the incident create modal the text fields are 20 and the dropdowns 16

**Comment by mainawycliffe** [comment]
@moshloop let me take care of this

**Comment by mainawycliffe** [comment]
@moshloop I have fixed the above issues.

**Comment by moshloop** [comment]
@mainawycliffe severity dropdown is still an issue:

**Comment by mainawycliffe** [comment]
@moshloop should look like this:

image

**Comment by moshloop** [comment]
@mainawycliffe On chrome for me it does not auto-select the first item for severity and results in a low height dropdown

**Comment by moshloop** [comment]
@mainawycliffe  - it is still an issue

**Pull request merged**
