### PR TITLE
feat: allow add comments as definition of done

### LINKED ISSUE #719: Manual Definition of Done
- Provide the ability to add a comment as a definition of done (either inline, or in the wizard)
- Allow comments to be manually resolved

### PR DESCRIPTION
**Pull request by mainawycliffe**
Closed #719

### CODE REVIEW

**Comment by moshloop** [comment]
@mainawycliffe 
- It looks like it creates a new hypothesis? 
- The styling on doesn't look very consistent - The 3 options should look the same, it think it might be better to have a 1st page wizard which lets you select the type, and then the next page which one (or in the case of manual, just the comment) - The comment should be limited to 50 chars otherwise the rendering will be bad
- The icon should be different, maybe a human to indicate a human needs to perform it?
- There should be an option to mark as done / unmark as done

**Comment by moshloop** [comment]
@mainawycliffe  Can we change it from a textarea to a text input ? And also make the tick green ?

**Comment by moshloop** [comment]
Just a plain input - in v2.0 we might assign these to responders but not for this release

**Comment by mainawycliffe** [comment]
@moshloop done

**Pull request merged**
