### PR TITLE
Fix/modal improvements

### PR DESCRIPTION
**Pull request by DmitriiMelnikOnix**
#122

### CODE REVIEW

**Review by moshloop — CHANGES_REQUESTED** [review]
Please create an example demonstrating these 2:

*  Full (Full-screen height - gap based on the screen size full-screen width - gap to a max of 1024
* Header and footer sections must be fixed on the modal body scrolls

**Comment by moshloop** [comment]
Please check the style the padding around the buttons in the footer looks wrong, there is also a ghost sidebar, and the full size needs to stretch to the full height of the page, only the width is limited to 1024

Can you also add an example with lots of text to see how the scroll works ?

**Comment by DmitriiMelnikOnix** [comment]
@moshloop I can't find the ghost sidebar. Can you take a screenshot?

**Comment by moshloop** [comment]
@DmitriiMelnikOnix 
Screenshot 2022-03-11 at 08 48 16
Screenshot 2022-03-11 at 08 47 39


The gap between the bottom of the dialog and the window is also missing

**Comment by DmitriiMelnikOnix** [comment]
> The gap between the bottom of the dialog and the window is also missing

The gap is exist if close netlify menu. I don't think this menu needs to be taken into account. It is only in deploy-preview

**Comment by moshloop** [comment]
@VincentWild69 please can you sign the CLA ?

**Pull request merged**
