### PR TITLE
FLNK-872 - Form - Health - Prometheus

### LINKED ISSUE #872: Form - Health - Prometheus

### PR DESCRIPTION
**Pull request by gitstart-flanksource**
Closes #872

### CODE REVIEW

**Comment by mainawycliffe** [comment]
@gitstart-flanksource a few things:

- name should come before the description field, check other forms that have been added to see the layout examples,
- for fields, here are the fields that are needed  https://docs.flanksource.com/canary-checker/reference/alert-manager/

**Comment by gitstart-flanksource** [comment]
Thanks for the feedback @mainawycliffe, we are on it.

**Comment by gitstart-flanksource** [comment]
Your feedback has been implemented @mainawycliffe

**Comment by mainawycliffe** [comment]
@gitstart-flanksource schedule field is missing now, that's needed and needs to map similar to the HTTP form

image

**Comment by gitstart-flanksource** [comment]
> @gitstart-flanksource schedule field is missing now, that's needed and needs to map similar to the HTTP form
> 
> image

Thanks for pointing that out @mainawycliffe, I'll get right on it.

**Comment by gitstart-flanksource** [comment]
Your feedback has been implemented, @mainawycliffe

**Comment by moshloop** [comment]
Does not save

**Pull request closed without merging**
