### PR TITLE
Feat: collapsible side nav panel

### PR DESCRIPTION
**Pull request by DmitriiMelnikOnix**
#163

### CODE REVIEW

**Comment by DmitriiMelnikOnix** [comment]
@moshloop what logo should I use for the collapsed menu?

**Comment by moshloop** [comment]
@DmitriiMelnikOnix https://raw.githubusercontent.com/flanksource/website2.0/master/v2/src/assets/images/flanksource-icon.svg

**Comment by moshloop** [comment]
@DmitriiMelnikOnix tooltips look good, still need to add saving the collapsed state in local storage

**Comment by moshloop** [comment]
@DmitriiMelnikOnix  I was referring to the uncollapsed logo - It should fit to width with around 12 - 16px padding, the collapsed icon with 12px padding

**Comment by moshloop** [comment]
@DmitriiMelnikOnix  looks good - please rebase

**Pull request merged**
