### PR TITLE
1393-add-icon-config-scrapers

### LINKED ISSUE #1393: Add icon for config scrapers

### PR DESCRIPTION
**Pull request by mainawycliffe**
Closes #1393

### CODE REVIEW

**Comment by moshloop** [comment]
@mainawycliffe - I don't see the icons anywhere ?

**Comment by mainawycliffe** [comment]
@moshloop they field? Should be next to the schedule field, inside the form section

**Comment by moshloop** [comment]
@mainawycliffe config scrapers don't need an icon field, they need in icon the table in the same way connections have a connection icon in the table

**Comment by mainawycliffe** [comment]
Ah, I see. Will make the changes.

**Comment by mainawycliffe** [comment]
What will the icon be based on, the name?

**Pull request merged**
