### PR TITLE
Feat: styles for small and large cards

### PR DESCRIPTION
**Pull request by DmitriiMelnikOnix**
#141

### CODE REVIEW

**Comment by moshloop** [comment]
The layout does not look right - the metrics are always horizontal. never vertical

**Comment by DmitriiMelnikOnix** [comment]
> The layout does not look right - the metrics are always horizontal. never vertical

It seems that the `grid-cols-3` class was not applied in the preview version. It is very strange. I replaced `grid` to `flex`

**Comment by moshloop** [comment]
@DmitriiMelnikOnix looks better now  but the topology selector modal still is not showing the checkboxes for selection

**Comment by moshloop** [comment]
@DmitriiMelnikOnix the checkboxes are fixed, but when clicking add the dialog does not close

**Comment by moshloop** [comment]
@OleksandrSekker please can you sign the CLA ?

**Pull request merged**
