### PR TITLE
fix: make health page layout responsive

### PR DESCRIPTION
**Pull request by gitstart**
Closes issue [#1007](https://github.com/flanksource/flanksource-ui/issues/1007)

[Loom Video](https://www.loom.com/share/0759e13d7959414fb03eb546385f19d6)

---
This code was written and reviewed by GitStart Community. Growing great engineers, one PR at a time.

### CODE REVIEW

**Comment by gitstart** [comment]
@moshloop This PR is ready for review

**Comment by moshloop** [comment]
@gitstart The current layout should be preserved, only on smaller screens where the layout breaks should it change

**Comment by gitstart** [comment]
> @gitstart The current layout should be preserved, only on smaller screens where the layout breaks should it change

Thanks for the feedback @moshloop, your comment has been addressed.

**Comment by moshloop** [comment]
@gitstart  ast 1280x960 the filters panel overlaps:
Screenshot 2023-04-25 at 09 11 35


The Health, last transition, uptime, latency columns can all shrink to width and the name column growing to the balance

**Comment by gitstart** [comment]
> @gitstart ast 1280x960 the filters panel overlaps: Screenshot 2023-04-25 at 09 11 35
> 
> The Health, last transition, uptime, latency columns can all shrink to width and the name column growing to the balance

This has been fixed @moshloop, thanks for the feedback.

**Comment by moshloop** [comment]
@gitstart this table still scrolls horizontally at 1280px width

**Comment by gitstart** [comment]
@moshloop Thanks for the feedback. The latest commit should resolve the issue.

Here is a loom video for reference: https://www.loom.com/share/7ba0127d461a4acca30f4e66dd8fa848?sid=e9399cf0-793f-40ec-acb9-2bb3123ae163

**Pull request closed without merging**
