### PR TITLE
feat: add side panel for topology page

### LINKED ISSUE #481: Topology Detail v2.0
Master-Detail Cards

### PR DESCRIPTION
**Pull request by mainawycliffe**
Closes #481

### CODE REVIEW

**Comment by mainawycliffe** [comment]
@moshloop this is almost ready; just one thing remaining in terms of Topology Details: We have the icon section and list below. Do we want to exclude the ones with a headline set true from the details list and only show them on the icon section? Secondly, where do the icons for the icon section come from?

**Comment by moshloop** [comment]
> Do we want to exclude the ones with a headline set true from the details list and only show them on the icon section?

yes

> where do the icons for the icon section come from?

these would come from the property.icon field

**Comment by mainawycliffe** [comment]
Thanks. I will take care of those.

**Comment by moshloop** [comment]
@mainawycliffe  The metrics are still missing: 

Screenshot 2022-10-14 at 11 27 43

**Pull request merged**
