### PR TITLE
1166-config-list-switch-new-config-summary-view

### LINKED ISSUE #1166: Config list - Switch to new config summary view

### LINKED ISSUE #1299: Config changes tab is missing icons

### PR DESCRIPTION
**Pull request by mainawycliffe**
Closes #1166
Closes #1299

### CODE REVIEW

**Comment by moshloop** [comment]
@mainawycliffe can we make only the table body scroll, not the entire table ?
Screenshot 2023-06-13 at 14 49 58

**Comment by mainawycliffe** [comment]
@moshloop the header is already sticky 
https://www.loom.com/share/e54983064c2e4a379b16b3bbd76d257d?sid=2529702d-b63e-47fc-9558-a52187c8206b

**Comment by mainawycliffe** [comment]
@moshloop can you take a look at this and let me know if it's what you wanted

**Comment by moshloop** [comment]
@mainawycliffe 
- In the header it still shows: `[k8 icon] Kubernetes::Pod`, I am expecting `[k8 icon] / [pod icon] Pod`
- The created at columns seems to be showing updated at value
- The switch in table width is too jarring, I think lets just keep it wide  - https://github.com/flanksource/duty/issues/193 will aslo add in max created/updated
- The cost is not reflecting

**Comment by moshloop** [comment]
@mainawycliffe the summary table is still centered and not full width ?

**Comment by mainawycliffe** [comment]
@moshloop I haven't pushed the changes yet

**Comment by mainawycliffe** [comment]
@moshloop this is good to go now

**Comment by moshloop** [comment]
@mainawycliffe - The cost is not pulling through correctly, and I am still seeing a full config listing.

**Pull request merged**
