### PR TITLE
fix: re-order change and analysis modal titles and add overflow

### LINKED ISSUE #1379: Change/Analysis Modal title with long resource names wraps
change the order so that it is change -> config (with overflow ellipsses) ? - I think it would apply to analysis dialog as well

### PR DESCRIPTION
**Pull request by mainawycliffe**
Overflow on last item now shows ellipses

Closes #1379

### CODE REVIEW

**Comment by moshloop** [comment]
@mainawycliffe  can you check the catalogs panel - we seem to have lost the overflow ellipses there
Screenshot 2023-09-18 at 10 25 17

**Comment by mainawycliffe** [comment]
@moshloop which link is this? I am looking for one to check if it's fixed, can't find one with long catalog names in the panel.

**Comment by moshloop** [comment]
@mainawycliffe  https://deploy-preview-1405--goofy-euclid-75956c.netlify.app/catalog/018848bc-7889-90cb-03f3-b2c21766fa23

**Comment by moshloop** [comment]
@mainawycliffe It looks like we also have a modal overflow issue if you click on one of the AttachVolume events - can we not force all modal bodies globally to scroll overflow ?

Screenshot 2023-09-19 at 12 14 45

**Comment by mainawycliffe** [comment]
@moshloop let me re-design the modal for this, it should be straight forward to achieve that for the modals.

**Pull request merged**
