### PR TITLE
fix: save referer id as query params

### PR DESCRIPTION
**Pull request by Prashanth-Nelli**

### CODE REVIEW

**Comment by moshloop** [comment]
@Prashanth-Nelli I don't think this is working: https://deploy-preview-581--goofy-euclid-75956c.netlify.app/topology/0183bfe6-8210-6333-8368-9658c5c4e402?status=healthy&refererId=0183bfe6-153f-11f6-8f65-6973361db2ba - I am expecting it to show "Redis" as the parent not pods.

**Comment by Prashanth-Nelli** [comment]
> @Prashanth-Nelli I don't think this is working: https://deploy-preview-581--goofy-euclid-75956c.netlify.app/topology/0183bfe6-8210-6333-8368-9658c5c4e402?status=healthy&refererId=0183bfe6-153f-11f6-8f65-6973361db2ba - I am expecting it to show "Redis" as the parent not pods.

@moshloop I am sending refererId as query param while fetching topology. But the backend is not returning proper response here.

Screenshot 2022-11-16 at 11 36 25 AM

**Comment by moshloop** [comment]
@Prashanth-Nelli the refererId is not for the backend, its for the frontend only to use the local component name cache to build the breadcrumbs

**Comment by moshloop** [comment]
@Prashanth-Nelli  I think we will also need to show the parent component in the sidebar details when parent != refererid

**Pull request merged**
