### PR TITLE
feat: show toast animation when navigating topology

### LINKED ISSUE #505: Topology - Add top of page bouncing progress bar - full width
e.g. something like http://nanobar.jacoborus.codes/

### PR DESCRIPTION
**Pull request by mainawycliffe**
Closes #505

### CODE REVIEW

**Comment by moshloop** [comment]
Why do we need this ? How is this different to the refresh button or the skeleton ?

**Comment by mainawycliffe** [comment]
While topology is loading and there was another topology being displayed, we don't show the loader, we show the existing topology until the other one is loaded, and the user is left wondering whether clicking worked. So, we can either do what I have done here or just show a skeleton as soon as the user navigates to another topology

**Comment by moshloop** [comment]
I don't see what this is doing? Can you record a video. 

I did not that the sidepanel loads, and then the topology cards are updated - We should probably only show the side panel when those details are retrieved, and empty the existing components before sending the load request (only for chaging the id, for all other filter changes the loading indicator at the top should be enough

**Comment by mainawycliffe** [comment]
The animation is at the bottom center of the screen. As shown below:

https://user-images.githubusercontent.com/12270550/198031840-b7744961-3b3b-4e87-8d4e-3c3be1269c73.mp4

**Comment by mainawycliffe** [comment]
> We should probably only show the side panel when those details are retrieved, and empty the existing components before sending the load request (only for chaging the id, for all other filter changes the loading indicator at the top should be enough

Yeah, this should work.

**Pull request closed without merging**
