### PR TITLE
feat: show config details, changes, analysis on config details page

### LINKED ISSUE #460: Config Detail v2.0
- [ ] Add name / dates / labels etc into main page (it only shows the actual JSON config at the moment)
- [ ] Add a panel  showing all analysis (with description and age)
- [ ] Add a panel with related config items (icon and name)
- [ ] Add a panel with related components (icon and name)

### PR DESCRIPTION
**Pull request by mainawycliffe**
WIP

Closes #460

### CODE REVIEW

**Comment by moshloop** [comment]
@mainawycliffe 
- [ ] The description of the analysis should be available on tooltip
- [ ] The side panel and the main body should not scroll together

**Comment by mainawycliffe** [comment]
@moshloop This is good to go now, I made the sidebar sticky

**Comment by moshloop** [comment]
@mainawycliffe - The tooltip on the analysis should show the message, not the name

**Comment by mainawycliffe** [comment]
@moshloop I have defaulted it to the message name, when there is no message. Should I default it to none?

**Comment by mainawycliffe** [comment]
Let me see if there is a mismatch on the code on how I am handling it.

**Comment by mainawycliffe** [comment]
Should be good now; my mistake on the field referencing.

**Comment by mainawycliffe** [comment]
Sure, does this work?
image

**Pull request merged**
