### PR TITLE
feat: add playbook runs page

### LINKED ISSUE #1354: Playbooks page
Add a Playbooks menu to the main sidebar, 

- It shows a table of playbook runs, click on a playbook run takes you to a playbook run detail page (Similar to a Azure Devops / Github actions runner progress page) showing each step, (its status and runtime) and the results of the step.

### PR DESCRIPTION
**Pull request by mainawycliffe**
WIP

Closes #1354

### CODE REVIEW

**Comment by moshloop** [comment]
I think we should have 2 tabs on the playbook page - One called Playbooks (which is basically the settings page) and another called Runs

**Comment by moshloop** [comment]
- [ ] On https://deploy-preview-1368--flanksource-demo-stable.netlify.app/playbooks/runs/018acdc5-65ee-da13-86b4-adea3da9cce0 clicking on the first action results in an error
- [ ] Need a header with the details of the run e.g. component, parameters, start date, status, duration
- [ ] On action list - only display duration (not start and end) - Maybe when clicking on the action to show the results we can display full start end and
- [ ] Run list should have Date and duration
- [ ] Run list name column is too short, all other columns should shrink to width

**Comment by moshloop** [comment]
@mainawycliffe - please resolve conflicts

**Comment by adityathebe** [comment]
@mainawycliffe the result page always shows "No Result" even if there's a successful result

image

**Comment by mainawycliffe** [comment]
@adityathebe can you give me the link for the above playbook run? If local, may be just send me the API response

**Comment by adityathebe** [comment]
@mainawycliffe It's on local

```json
[
    {
        "id": "018b1d16-1564-6c43-71d1-0eb8b50300b1",
        "playbook_id": "70c6e8a4-2366-4532-95f3-e2fefbcad58c",
        "status": "completed",
        "created_at": "2023-10-11T04:54:28.452112+00:00",
        "start_time": "2023-10-11T04:54:28.452112+00:00",
        "end_time": "2023-10-11T04:54:28.455698+00:00",
        "created_by": "d87243c9-3183-4ab9-9df9-c77c8278df11",
        "config_id": null,
        "component_id": "018af3d5-3726-217f-6728-fae773993b62",
        "parameters": null,
        "agent_id": null,
        "check_id": null,
        "created_by": {
            "id": "d87243c9-3183-4ab9-9df9-c77c8278df11",
            "name": "Admin ",
            "avatar": null
        },
        "playbooks": {
            "id": "70c6e8a4-2366-4532-95f3-e2fefbcad58c",
            "name": "count-event-queue"
        },
        "component": {
            "id": "018af3d5-3726-217f-6728-fae773993b62",
            "name": "adityathebe",
            "icon": "kubernetes"
        },
        "actions": [
            {
                "id": "018b1d16-1568-6469-62d5-42010eb2ef52",
                "name": "Post a message to webhook",
                "status": "completed",
                "playbook_run_id": "018b1d16-1564-6c43-71d1-0eb8b50300b1",
                "start_time": "2023-10-11T04:54:28.455698+00:00",
                "end_time": "2023-10-11T04:54:28.455698+00:00",
                "result": {
                    "rows": [
                        {
                            "count": "1"
                        }
                    ],
                    "count": 1
                },
                "error": null
            }
        ]
    }
]
```

**Comment by mainawycliffe** [comment]
@adityathebe is okay now?

**Comment by adityathebe** [comment]
@mainawycliffe Need to decide on this https://github.com/flanksource/incident-commander/pull/587#discussion_r1356401424

but the results are showing up now

**Comment by mainawycliffe** [comment]
I think we can contain the overflow to the display section

**Comment by mainawycliffe** [comment]
@adityathebe try now and let me know how that looks like

**Comment by adityathebe** [comment]
@mainawycliffe 

image

**Comment by moshloop** [comment]
@mainawycliffe  merging, please create new issues for the remaining items

**Pull request merged**
