### PR TITLE
Fix-dropdown-empty-resource-selector

### PR DESCRIPTION
**Pull request by mainawycliffe**

### CODE REVIEW

**Comment by adityathebe** [comment]
@mainawycliffe the resource selector works. However there's also an invalid request to `/search` immediately after. It's sending `type: string` whereas it should be sending `types: []string`.

This is on playbook parameter type "config"

image

**Comment by mainawycliffe** [comment]
@adityathebe the incorrect search would only from an incorrect spec, we pass the content of configs/checks/component directly to the resource selector, without modifying it.

image

**Review by adityathebe — APPROVED** [review]

**Comment by mainawycliffe** [comment]
@adityathebe This could also be the reason for the second erroneous one

image

**Comment by adityathebe** [comment]
> @adityathebe This could also be the reason for the second erroneous one
> 
> image

yea, I've fixed the property for the `config` parameter and it's working now.

**Pull request merged**
