### PR TITLE
fix: show correct data for created at and updated at columns on canary settings page

### LINKED ISSUE #939: Canary settings page shows NaN for Created and Updated At
image

### PR DESCRIPTION
**Pull request by gitstart**
Part of #939

**Previous with issue:**

**Fixes:**
Screenshot from 2023-03-22 20-31-39

---
This code was written and reviewed by GitStart Community. Growing great engineers, one PR at a time.

### CODE REVIEW

**Comment by gitstart** [comment]
@yashmehrotra this PR is ready for review. Cc @moshloop

**Comment by mainawycliffe** [comment]
@gitstart I am unable to rebase this on my end, can you do it.

**Comment by gitstart** [comment]
> @gitstart I am unable to rebase this on my end, can you do it.

Done @mainawycliffe

**Review by mainawycliffe — APPROVED** [review]
LGTM

**Pull request merged**
