### PR TITLE
656-component-dropdown-should-show-none-instead-of-all

### LINKED ISSUE #656: In Logs Table, Component dropdown should show none instead of all
Since we don't show all logs but rather one per component, the default entry should switch to none instead of all

image

### PR DESCRIPTION
**Pull request by DesmondSanctity**
Closes #656 

image

### CODE REVIEW

**Comment by mainawycliffe** [comment]
One more thing, we probably need to show the value none when none is selected instead of an empty input 
image

**Comment by DesmondSanctity** [comment]
> One more thing, we probably need to show the value none when none is selected instead of an empty input image

Okay. I will check that.

**Comment by DesmondSanctity** [comment]
I have fixed that.

image

**Comment by mainawycliffe** [comment]
@DesmondSanctity please rebase against the latest changes on the main branch

**Comment by DesmondSanctity** [comment]
okay

**Review by mainawycliffe — APPROVED** [review]

**Comment by mainawycliffe** [comment]
@DesmondSanctity Thanks for the PR

**Pull request merged**
