### PR TITLE
feat: JUnit viewer

### PR DESCRIPTION
**Pull request by DmitriiMelnikOnix**
#71

### CODE REVIEW

**Comment by moshloop** [comment]
@DmitriiMelnikOnix Can we put this into a sortable tree-table with columns for description, descriptions, and Summary (passed/failed) ?

**Comment by DmitriiMelnikOnix** [comment]
@moshloop do you have any more JSON examples with failed or other cases?

**Comment by moshloop** [comment]
@DmitriiMelnikOnix it is the same date e.g.

`Untitled suite in /Users/niko/Sites/casperjs/tests/suites/casper/agent.js
(2/3)
0.256ms`

`2` is passed, `3` is total ( so not passed/total, keep as is passed/total)

**Comment by DmitriiMelnikOnix** [comment]
@moshloop can I use the `Table` component from `src/components/Canary/table.js` or should I create a new tree-table component?

**Comment by moshloop** [comment]
@DmitriiMelnikOnix I think create a new tree table component use react-table expansion or another tree-component if that doesn't work

**Comment by DmitriiMelnikOnix** [comment]
@moshloop do you have any style preference for the table? Is there some example of which I can take the styles for the table?

**Comment by moshloop** [comment]
@DmitriiMelnikOnix you can use https://docs.microsoft.com/en-us/azure/devops/pipelines/test/review-continuous-test-results-after-build?view=azure-devops as a reference

**Comment by moshloop** [comment]
Also the hierarchy is based on suite.name ->  (group by test.classname) -> test.name

**Comment by moshloop** [comment]
@DmitriiMelnikOnix  looking better, however:

1) In this screenshot the last row should be indented under `tests/suites/casper/agent`
Screenshot 2022-03-30 at 07 59 04

2) Missing counts per level
3) Missing duration column

**Comment by moshloop** [comment]
@DmitriiMelnikOnix  looking better - Can we format the duration? 
Also the count should be passed of total, not failed of total, 
The counts should also rollup to the top so a parent count = sum(children)

**Comment by moshloop** [comment]
@DmitriiMelnikOnix - looking good, can we add a filter to hide passing tests (with a param to to the combonent that defaults to hidePassing) and another parameter to hide the header with pass/failed etc ?

**Comment by moshloop** [comment]
@DmitriiMelnikOnix  the failed count in this screenshot should be 1 not 0

Screenshot 2022-04-17 at 10 25 05

**Comment by moshloop** [comment]
@DmitriiMelnikOnix The hide header option should not hide the status column, it should hide the header with Failed / Passed / Total count status etc..

**Comment by DmitriiMelnikOnix** [comment]
> @DmitriiMelnikOnix the failed count in this screenshot should be 1 not 0

It was a data error. Initially all tests were passed and I added failed test to check the table

**Pull request merged**
