### PR TITLE
Fix-incident-severity-bug-on-incident-create

### PR DESCRIPTION
**Pull request by mainawycliffe**

### CODE REVIEW

**Comment by moshloop** [comment]
@mainawycliffe can you check the priority/severity combo on incident details it is rendering empty ?

**Comment by mainawycliffe** [comment]
@moshloop cool

**Comment by mainawycliffe** [comment]
@moshloop should be good now, it was another source of number severity and was the reason the issue was occuring

**Comment by moshloop** [comment]
@mainawycliffe The dropdown now matches the full list of severities, but it still shows as empty

**Comment by mainawycliffe** [comment]
@moshloop are we talking about this part here?
image

**Pull request merged**
