### PR TITLE
chore: fix logs page continuous request

### PR DESCRIPTION
**Pull request by richardsaseun14**

### CODE REVIEW

**Comment by richardsaseun14** [comment]
@moshloop I have been able to stop the continuous API call but the apm/search call is returning an Internal Server Error after running for a minute.

image

**Comment by moshloop** [comment]
@richardsaseun14  can you fix the linting error and maybe add a storybook for this component with a storybook request mock for the backend using this data: https://gist.github.com/moshloop/929bc1b72e793c95ddbc2d6ee5425761 ?

**Comment by richardsaseun14** [comment]
> @richardsaseun14  can you fix the linting error and maybe add a storybook for this component with a storybook request mock for the backend using this data: https://gist.github.com/moshloop/929bc1b72e793c95ddbc2d6ee5425761 ?

@moshloop I will jump on the linting errors but what particular component do you want me to add storybook for?

**Comment by moshloop** [comment]
@richardsaseun14  the LogViewer component

**Comment by richardsaseun14** [comment]
@moshloop The LogsViewer component already has a storybook created but I have added the log from the gist you posted to the it.

**Comment by richardsaseun14** [comment]
@moshloop waiting for this PR to be closed or is there any other thing you will like me to do.

**Pull request closed without merging**
