### PR TITLE
Add Storybook

### PR DESCRIPTION
**Pull request by moshloop**

### CODE REVIEW

**Comment by moshloop** [comment]
@VincentWild69  can you sign the CLA ?

@DmitriiMelnikOnix this looks good - it is a good start:

1. Can we get this action to publish working: https://github.com/flanksource/flanksource-ui/runs/6082004418?check_suite_focus=true
2. I don't think the tailwind themes are loading
3. Can we test and make sure component loads and that all the popups work i.e. the correct test data has been added

**Comment by VincentWild69** [comment]
@moshloop
> * I don't think the tailwind themes are loading
I don't quite understand what you mean, can you clarify where exactly you see the problem?

**Comment by moshloop** [comment]
@VincentWild69  https://www.chromatic.com/build?appId=625ed6eb9d495f003acc84b4&uploadHash=uhvrmocjcq

**Comment by VincentWild69** [comment]
@moshloop I checked this component, the problem is in its syntax, not in the styles. This component is not suitable for display in the storybook,  I removed it.

**Comment by moshloop** [comment]
@VincentWild69 Please see the UI review, the screencaps are not tailwind styled, and there is a failing component

**Comment by moshloop** [comment]
@VincentWild69 @DmitriiMelnikOnix I am merging this so long, so that we can rebase our PR's with stories - but please fix those issues

**Pull request merged**
