### PR TITLE
feat: add incident summary to topology card

### LINKED ISSUE #407: Topology Card - Add incident summary
Add cell that shows counts of open incidents (by type) use the component_incidents view

### PR DESCRIPTION
**Pull request by mainawycliffe**
Closes #407

### CODE REVIEW

**Comment by moshloop** [comment]
Can we style this more to look like the others i.e.  `{Incidents Icon} Incidents  [ 1 ]` and group by severity - when clicking on it should take you to the incidents page with the component and severity filtered

**Comment by mainawycliffe** [comment]
Yeah, let me do that.

**Comment by mainawycliffe** [comment]
@moshloop let me have a look first thing in the morning

**Comment by mainawycliffe** [comment]
@moshloop do you want me to also have a look at updating the query on the backend?

**Pull request merged**
