### PR TITLE
FLNK-1092 - Display analysis JSON

### PR DESCRIPTION
**Pull request by gitstart-flanksource**
Closes: [1092](https://github.com/flanksource/flanksource-ui/issues/1092)

###### BEFORE:

image

###### AFTER:

https://github.com/GitStartHQ/client-flanksource/assets/57623705/0cf58a77-438b-4ff4-812f-56e5095982a6

### CODE REVIEW

**Comment by adityathebe** [comment]
Looks nice but I think the height can be increased.

**Comment by moshloop** [comment]
This PR shows the config JSON, it should have another tab called Raw that shows the contents of the config_analysis.analysis column

**Comment by gitstart-flanksource** [comment]
> This PR shows the config JSON, it should have another tab called Raw that shows the contents of the config_analysis.analysis column

@moshloop your feedback has been implemented.

**Comment by moshloop** [comment]
The config does not need to be shown in the popup, I am expecting 2 tabs (Summary and Raw) summary displays what is current shown in the body, and raw is the analysis object.  If the analysis object is null or empty (`{}`) then the tabs should not be shown and it should look like it does now

**Comment by gitstart-flanksource** [comment]
Thanks for the feedback @moshloop, we are on it.

**Comment by gitstart-flanksource** [comment]
Your feedback has been implemented @moshloop

**Pull request closed without merging**
