### PR TITLE
chore: create config history table on config page using tabs and close #188

### LINKED ISSUE #188: Config Viewer - Show history table
Based on config_changes

### PR DESCRIPTION
**Pull request by richardsaseun14**
Add the config history table to the config viewer.
image

### CODE REVIEW

**Comment by moshloop** [comment]
@richardsaseun14  So these changes are linked to s a specific config item i.e. when you click on an item it takes you take a page with 2 tabs, 1 for the content of the item, and 1 for changes that have been applied to the item

**Comment by richardsaseun14** [comment]
@moshloop i have reverted the changes.

**Comment by moshloop** [comment]
@richardsaseun14 - Could you try adding a storybook for the page and components ?

**Comment by richardsaseun14** [comment]
@moshloop Done creating all the component stories on the page

**Pull request closed without merging**
