### PR TITLE
feat: create a loading skelton for full page animation

### LINKED ISSUE #458: Add loading skeleton (pre all javascript)

### PR DESCRIPTION
**Pull request by mainawycliffe**
Closes #458

### CODE REVIEW

**Comment by mainawycliffe** [comment]
@moshloop is this what we had in mind in terms of the task #458?

**Comment by moshloop** [comment]
Yeh, can we also implement it for topology and  health page ?

**Comment by mainawycliffe** [comment]
Sure

**Comment by mainawycliffe** [comment]
@moshloop I have added the skelton loader for both topology and health page, let me know what you think. Do we need to do it for incidents and config pages as well?

**Comment by moshloop** [comment]
On the health page can use the same same centering styles, on a wide screen the skeleton is left aligned and the actual content is centered

**Comment by mainawycliffe** [comment]
Let me do that.

**Comment by moshloop** [comment]
@mainawycliffe health page is still an  issue

**Comment by mainawycliffe** [comment]
Working on this right now

**Pull request merged**
