### PR TITLE
fix: split type to get primary and secondary icons

### LINKED ISSUE #1113: Config type icons / name
Split by `::` and then do lookup for both

e.g. `Kubernetes::Certificate` becomes:

{K8S Icon} / {Certificate Icon} Certificate

### PR DESCRIPTION
**Pull request by mainawycliffe**
Closes #1113

### CODE REVIEW

**Comment by moshloop** [comment]
@mainawycliffe - I am expecting to see 2 icons, and for the prefix to be stripped off, 

The 2nd icon name={full type}, secondary={split(::)[1]}

**Comment by mainawycliffe** [comment]
@moshloop is this what you had in mind?

**Comment by moshloop** [comment]
@mainawycliffe still need to drop the first prefix e.g. 'Kubernetes::'

**Comment by moshloop** [comment]
Screenshot 2023-05-16 at 17 29 19
Screenshot 2023-05-16 at 17 29 25

@mainawycliffe still looks like there are issues

**Comment by moshloop** [comment]
@mainawycliffe - Can we add a max height and a max width? the sizing doesn't seem very consistent

**Pull request merged**
