### PR TITLE
fix: make home link to retain search/order state

### PR DESCRIPTION
**Pull request by gitstart**
Closes issue [#438](https://github.com/flanksource/flanksource-ui/issues/438)

[Loom Video](https://www.loom.com/share/ef49e73203b74c6bbb303ac33e0ca9d3)

---
This code was written and reviewed by GitStart Community. Growing future engineers, one PR at a time.

### CODE REVIEW

**Comment by gitstart** [comment]
@moshloop this PR is ready for review

**Comment by moshloop** [comment]
@gitstart this works for the scenario when you arrive at the detail page from the list, but if I arrive at the detail page from a perm-link, then the home takes me nowwhere not to the config page

**Comment by moshloop** [comment]
@gitstart this is still not working

**Comment by gitstart** [comment]
@moshloop you can see our implementation in this loom video

https://www.loom.com/share/7a1efe8ce20f44d5835f497ddb578a61

**Comment by gitstart** [comment]
What's the verdict on this? @moshloop

**Comment by moshloop** [comment]
This approach does not work as there are too many edge cases

**Pull request closed without merging**
