### PR TITLE
1060-sidebar-improvements-collapse-items-apart-default

### LINKED ISSUE #1060: Sidebar Improvements - Collapse All Items apart from default
- [ ]  Collapse Item in an accordion sort of approach, opening only one panel and the user can expand the rest as need be
- [ ] Add distinction between the panel - add underline at the end of the panel content

### LINKED ISSUE #1071: Topology refresh button doesn't refresh side-panels

### LINKED ISSUE #1077: Topology sidebar: Insights panel ui is broken
Screenshot 2023-04-13 at 10 53 19 AM

### PR DESCRIPTION
**Pull request by mainawycliffe**
Closes #1060
Closes #1077 
Closes #1071 

@moshloop is this what you had in mind?

### CODE REVIEW

**Comment by moshloop** [comment]
@mainawycliffe can you resolve conflicts ?

**Comment by mainawycliffe** [comment]
@moshloop this is good to go now

**Comment by moshloop** [comment]
@mainawycliffe The collapsing of the panel itself should transition as well  not just the body, 

For the count badges can we switch to a style similar to on the topology cards (rectangle that grows with content) - or shrink the font-size to fit

**Comment by moshloop** [comment]
@mainawycliffe can we time the close transition to run in parallel to the open ?

**Comment by mainawycliffe** [comment]
@moshloop sure

**Comment by mainawycliffe** [comment]
@moshloop What do you think?

**Comment by moshloop** [comment]
@mainawycliffe we seem to have lost the scrollbar on changes ?

**Comment by mainawycliffe** [comment]
@moshloop I have reverted back animations to what it was and everything should be good to go now.

**Pull request merged**
