### PR TITLE
fix: config changes listing layout issues

### PR DESCRIPTION
**Pull request by Prashanth-Nelli**

### CODE REVIEW

**Review by mainawycliffe — APPROVED** [review]
LGTM

**Comment by moshloop** [comment]
@Prashanth-Nelli we need to implement paging for this.

**Comment by Prashanth-Nelli** [comment]
@moshloop paging is implemented already. including the page screenshot for you reference.

Screenshot 2023-01-11 at 4 49 00 PM

**Comment by moshloop** [comment]
@Prashanth-Nelli I don't see it on the deploy preview - We should also not be showing any json in the table - that should. be in a popup only

**Comment by Prashanth-Nelli** [comment]
@moshloop config changes fetch api call is failing with below error on netlify previews.
`{
  "errorMessage": "Response payload size exceeded maximum allowed payload size (6291556 bytes).",
  "errorType": "Function.ResponseSizeTooLarge"
}`

**Pull request merged**
