### PR TITLE
refactor: use API properties endpoint instead of DB properties

### LINKED ISSUE #1880: Use the /properties endpoint instread of /db/properties

### LINKED ISSUE #1885: feature flag page sends large number of requests indefinitely
[Uploading](
https://github.com/flanksource/flanksource-ui/assets/13419481/651624b5-a487-47d6-a620-41bcdfdabbc9
)

### PR DESCRIPTION
**Pull request by mainawycliffe**
Fixes #1880
Fixes #1885

### CODE REVIEW

**Comment by moshloop** [comment]
@mainawycliffe - this is the wrong way around, the `/properties` should be used for feature flags, and for rendering the table, when creating / updating / deleting properties then we hit the DB endpoint - Unless `source=local` in which case you cannot create/update/delete the property as its overridden in local files on the server

**Comment by mainawycliffe** [comment]
@moshloop it's currently setup like that, apart from the source, field, which is missing, should I add that on duty?

**Comment by mainawycliffe** [comment]
@adityathebe can you can confirm this also fixes the following issue #1885

**Comment by moshloop** [comment]
@mainawycliffe clicking on add doesn't do anything - You also should not be able to add or edit a db property if there is a local

**Comment by adityathebe** [comment]
> @adityathebe can you can confirm this also fixes the following issue #1885

seems to be fixed 👍

**Pull request merged**
