### PR TITLE
#707 Setting up unit test with jest and react testing library

### LINKED ISSUE #707: Unit Testing Setup
- Add a unit testing framework
- Ensure the tests need to pass before PR's can be merged
- Add some initial coverage

### PR DESCRIPTION
**Pull request by DesmondSanctity**
Fixes #707 .

- Installed Jest testing framework and setup the config. Also added type configuration for jest in the tsconfig file.

- Moved existing tests to a new folder called __test__ . All unit test reside here.

- Add a PR trigger for all test in the CI yaml file to run before PR can be merged

### CODE REVIEW

**Comment by Prashanth-Nelli** [comment]
@DesmondSanctity please squash commits and create separate commits one for testing setup and the other for fixing failing test cases and also the commit message should be in a proper format. 

These details are documented here https://github.com/flanksource/style-guide/blob/master/docs/front-end.md

**Comment by DesmondSanctity** [comment]
> @DesmondSanctity please squash commits and create separate commits one for testing setup and the other for fixing failing test cases and also the commit message should be in a proper format.
> 
> These details are documented here https://github.com/flanksource/style-guide/blob/master/docs/front-end.md
> 
> please update failing storybooks.

Noted. I will fix that

**Comment by DesmondSanctity** [comment]
@Prashanth-Nelli please check now. Storybook is failing because of this error in the workflow log `Error: ✖ Missing project token`.

I do not have the token in my env I guess.

**Review by Prashanth-Nelli — APPROVED** [review]
LGTM.

@DesmondSanctity could you please rebase master into your branch.

**Comment by DesmondSanctity** [comment]
> LGTM.
> 
> @DesmondSanctity could you please rebase master into your branch.

Okay will do that

**Review by mainawycliffe — APPROVED** [review]
LGTM

**Comment by Prashanth-Nelli** [comment]
@DesmondSanctity thank you for the contributions, could you please rebase master into this branch. I'll merge this once you commit after rebasing.

**Comment by DesmondSanctity** [comment]
> @DesmondSanctity thank you for the contributions, could you please rebase master into this branch. I'll merge this once you commit after rebasing.

I think I don't have this branch again and I can't restore it.

What do we do?

**Comment by Prashanth-Nelli** [comment]
@DesmondSanctity create a new PR by checking out from the latest master.

**Comment by DesmondSanctity** [comment]
Okay

**Comment by DesmondSanctity** [comment]
@Prashanth-Nelli I recovered the repo. I think you can merge now.

**Pull request merged**
