### PR TITLE
649-add-topologycanaryscraper-history-tabs

### LINKED ISSUE #649: Add topology/canary/scraper history tabs
Depends on https://github.com/flanksource/incident-commander/issues/202

- Add a Settings -> Job page to view all jobs using a JobTable component that can be re-used
- Add a tab on the relevant settings screen to review the historical execution status and duration.

### PR DESCRIPTION
**Pull request by mainawycliffe**
Closes #649

### CODE REVIEW

**Comment by moshloop** [comment]
What is the difference between started and created ?

* Can we change the order to started (timestamp), job name, status, duration (with unit suffix)
* Use a small colored dot to indicate status with lowercase text
* Hide 0 errors, and color non 0 errors red
* Need a popup to show the error details  if any

**Comment by mainawycliffe** [comment]
@moshloop in terms of this:  Hide 0 errors, and color non 0 errors red, what do you mean, hide jobs with 0 errors?

**Comment by mainawycliffe** [comment]
@moshloop I have made requested changes

**Comment by mainawycliffe** [comment]
@moshloop for different settings, what resourceType and resourceId should I use for each setting item?

**Pull request merged**
