### PR TITLE
Time range picker

### PR DESCRIPTION
**Pull request by DmitriiMelnikOnix**
https://github.com/flanksource/flanksource-ui/issues/78

### CODE REVIEW

**Comment by moshloop** [comment]
@VincentWild69 please sign CLA

This is looking good - can we style it with the tailwind classes and theme ?

**Comment by VincentWild69** [comment]
@[moshloop](https://github.com/moshloop) For the calendar, which is used in the component, stylization is provided using classes prepared in advance in it. Therefore, the use of tailwind in this case is not appropriate. I also encountered a bug: some classes from tilewind do not work (for example: w-fit, some color schemes), and a different way of styling is needed to apply these properties. There are also quite a lot of interactive elements, and with the classic CSS file, working with them looks clearer. I used tailwind to the maximum, but in this case I think it is appropriate to leave some style in the css file, according to the arguments above.

**Comment by VincentWild69** [comment]
@moshloop Can we leave the styling as it is? ^

**Comment by moshloop** [comment]
@VincentWild69  I don't particularly care how the styling is done, but it must match the look and feel of the existing components If I put a dropdown and a timepicker next to each other they should look the same

**Comment by moshloop** [comment]
@VincentWild69  please rebase and add storybooks

**Comment by Prashanth-Nelli** [comment]
Handled this requirement in PR [78](https://github.com/flanksource/flanksource-ui/issues/78)

**Pull request closed without merging**
