### PR TITLE
fix: Added Team Members Don't Show Up in Teams Members Tab

### LINKED ISSUE #979: Added Team Members Don't Show Up in Teams Members Tab
On add a team member, there should be listed in the members tab 

https://user-images.githubusercontent.com/12270550/226571135-b3e9a3e2-54b2-4aab-9c21-002d97a76492.mp4

### PR DESCRIPTION
**Pull request by gitstart**
closes #979

**Demo:**
[Loom video](https://www.loom.com/share/9e447f46177849869bdb99efc1abab6b)

---
This code was written and reviewed by GitStart Community. Growing great engineers, one PR at a time.

### CODE REVIEW

**Comment by gitstart** [comment]
@mainawycliffe  This PR is ready for review Cc: @moshloop

**Comment by moshloop** [comment]
@gitstart there is a bit of a delay when adding and remove members (the success message is shown before the able updates) and also when opening the tab it is blank and then renders, whereas it should render and show loading state

**Comment by gitstart** [comment]
> @gitstart there is a bit of a delay when adding and remove members (the success message is shown before the able updates) and also when opening the tab it is blank and then renders, whereas it should render and show loading state

Thanks for the feedback @moshloop, your comments have been addressed.

**Comment by moshloop** [comment]
It seems the skeleton is still shown for every load, not just first load

**Comment by gitstart** [comment]
Thanks for the feedback @moshloop, your comment has been addressed.

**Pull request merged**
