### PR TITLE
feat: add filter by component for incidents list

### LINKED ISSUE #425: Incidents - Filter by component

### PR DESCRIPTION
**Pull request by mainawycliffe**
Closes #425

### CODE REVIEW

**Comment by mainawycliffe** [comment]
@moshloop is this what you had in mind?

**Comment by moshloop** [comment]
Yes - but switch to `component_names` rather than components - components table directly itself should never be called

**Comment by mainawycliffe** [comment]
Cool...let me make the change

**Comment by mainawycliffe** [comment]
@moshloop, it seems like the react-select is already set to popout for all controls

**Comment by moshloop** [comment]
@mainawycliffe  when show the value, I am not expecting a border it should be without a border and shrink to content, The popover should have a min width, and expand up to 400px with the content - Switching the component to be the first filter may also help

**Comment by mainawycliffe** [comment]
@moshloop I get you now.

**Comment by moshloop** [comment]
I am not seeing any changes ?

**Comment by mainawycliffe** [comment]
I haven't pushed the changes yet, still trying to localize the changes so they don't affect components in other places where were use the component. 
image

**Comment by mainawycliffe** [comment]
Is this what you had in mind?
image

**Comment by moshloop** [comment]
@mainawycliffe , yeh - Can we maybe move them right on top of the table like topology / health, and then order them in the same way the table columns are ordered ?

**Comment by mainawycliffe** [comment]
@moshloop Yeah, let me do that.

**Comment by mainawycliffe** [comment]
Done, at the moment, we don't have a column for components or owner, what do we do with those.

**Comment by moshloop** [comment]
@mainawycliffe  both the filter bar and table headers should be fixed, only the rows should scroll

**Comment by moshloop** [comment]
@mainawycliffe 

- when the page first loads, the filter bar and table is in the center of the page vs the top
- can we style the dropdowns like the health page group by / tab by i.e The label inside the field (excecpt the dropdown should still shrink to width

**Comment by mainawycliffe** [comment]
@moshloop is this what you mean? 
image

**Comment by moshloop** [comment]
@mainawycliffe remove the extra component label, make the background of the inputs white, and change the label text to gray-600

**Comment by mainawycliffe** [comment]
@moshloop something like this? 
image

**Pull request merged**
