### PR TITLE
UI updates to hypothesis bar

### PR DESCRIPTION
**Pull request by ciju**
- [x] Show count for multiple evidence of same type
- [x] Move delete, create solution actions to menu
- [x] Improve styling for side line to child hypothesis
- [x] Move edit action to menu
- [x] Can we switch back to the input with the tick or x to complete editing? Can we also make the input have some padding so it doesn't take up the full height of the bar
- [x] The hypothesis should expand/collapse on clicking on the title

Closes: https://github.com/flanksource/flanksource-ui/issues/328

### CODE REVIEW

**Comment by moshloop** [comment]
- [ ] Can we switch back to the input with the tick or x to complete editing? Can we also make the input have some padding so it doesn't take up the full height of the bar
- [ ] The hypothesis should expand/collapse on clicking on the title

**Comment by ciju** [comment]
Pushed the changes.

**Comment by moshloop** [comment]
* It looks like the click target is not the bar so if you click on the top or bottom of the bar, it doesn't do anything
* Can we expand the entire tree of children ?

**Comment by ciju** [comment]
Expanding all children is becoming tricky. Right now, it works if the page has `Show Comments` enabled. When disabled, click only expands current hypothesis node. If children need to be expanded in this case also, I can spend some more time on it.

**Comment by moshloop** [comment]
I don't think we should have a Show Comments, rather just a Expand / Collapse All

**Comment by ciju** [comment]
Updated with expand/collapse rewording.

**Comment by ciju** [comment]
Collapse expand behavior should be fixed now.

**Pull request merged**
