### PR TITLE
style: remove light grey bg at bottom of modals

### LINKED ISSUE #838: UI - remove light grey bg at bottom of modals
Screenshot 2023-02-28 at 15 03 59

The light grey background at the bottom of modals (often where the modal's action buttons live) conflicts with the same grey background of the modal header.

A solution could be to remove the bg colour and instead have a thin top border on that bottom section.

### PR DESCRIPTION
**Pull request by gitstart**
closes #838

Screenshot from 2023-03-07 14-36-31

---
This code was written and reviewed by GitStart Community. Growing future engineers, one PR at a time.

### CODE REVIEW

**Comment by gitstart** [comment]
@moshloop this PR is ready for review.

**Comment by moshloop** [comment]
@gitstart - can we add in the top light gray border in the footer ?

**Comment by gitstart** [comment]
> @gitstart - can we add in the top light gray border in the footer ?

@moshloop I already added the top right gray border in the footer, should I make the top border 2px so it can be more visible?

**Comment by gitstart** [comment]
@moshloop your feedback has been implemented, please check again.

**Pull request closed without merging**
