### PR TITLE
727 Logs page loading icon spinning when no component Is selected

### LINKED ISSUE #727: Minor UI Issues: The Logs Page Loading Button is Spinning when There is no Component Is Selected
image

### PR DESCRIPTION
**Pull request by DesmondSanctity**
Fixes #727

### CODE REVIEW

**Review by mainawycliffe — APPROVED** [review]
LGTM

**Comment by mainawycliffe** [comment]
@DesmondSanctity please rebase this against main and then I will merge it in.

**Comment by mainawycliffe** [comment]
@DesmondSanctity you can rebase by running the following commands:

```bash
git fetch upstream
git rebase upstream/main
```

**Comment by DesmondSanctity** [comment]
> @DesmondSanctity you can rebase by running the following commands:
> 
> ```shell
> git fetch upstream
> git rebase upstream/main
> git push -f origin <branch-name>
> ```

Ok. I did that and there was a new update to main after that. I wanted to reset the head to my last commit. So I will pull everything from main at once, guess I did a mistake.

**Comment by mainawycliffe** [comment]
Sorry about that, there have been a few merges going on over the last few minutes, it should be safe now.

**Comment by DesmondSanctity** [comment]
This push is current with main now.

**Comment by mainawycliffe** [comment]
@DesmondSanctity you seem to have snagged a couple of commits that do not belong

**Comment by DesmondSanctity** [comment]
> @DesmondSanctity you seem to have snagged a couple of commits that do not belong

I've squashed it to one commit.

**Pull request merged**
