### PR TITLE
fix: config change modal ui improvements

### LINKED ISSUE #1223: Change modal fixes
- External created by should be considered
- Height of modal should be 80% 
- Add padding around / editor

### PR DESCRIPTION
**Pull request by Prashanth-Nelli**
Closes #1223

### CODE REVIEW

**Comment by moshloop** [comment]
@Prashanth-Nelli The entire body of the modal now scrolls? The header and footer should always be fixed.

**Comment by moshloop** [comment]
@mainawycliffe - the dialog height should be larger, there is only a few lines displayed in the change and lots of scrolling. 
Created By should be first populated by created_by avatar or external_created_by - they are not different fields - Either way external created by is not showing - see https://deploy-preview-1232--goofy-euclid-75956c.netlify.app/configs/018848bc-7a1d-9ff4-833e-486916a86b29

**Comment by mainawycliffe** [comment]
@moshloop in the above example, created by is null in all changes

**Comment by moshloop** [comment]
@mainawycliffe  external created by is not.

**Comment by moshloop** [comment]
@mainawycliffe  - Can we move date to the first column, and not use up so much space (i.e. Date / Created By, fit to width, Source last and ellipses

- The "Details" label also seems to be cut off.
- Can we make the dialog a min height so that it doesn't show a tiny dialog and then always grow, - only grow when its

**Comment by mainawycliffe** [comment]
> @mainawycliffe  external created by is not. 

Yeah, in cases where it's available, it's displayed now

**Comment by mainawycliffe** [comment]
> @mainawycliffe  - Can we move date to the first column, and not use up so much space (i.e. Date / Created By, fit to width, Source last and ellipses
> 
> - The "Details" label also seems to be cut off.
> - Can we make the dialog a min height so that it doesn't show a tiny dialog and then always grow, - only grow when its 
> 
> 

Yeah, can do that

**Comment by moshloop** [comment]
@mainawycliffe it looks like we have lost the modal title now?

**Comment by mainawycliffe** [comment]
@moshloop that's fixed now

**Comment by moshloop** [comment]
@mainawycliffe I don't see any change?

**Comment by moshloop** [comment]
@mainawycliffe we seem to be missing the details now ?

**Comment by moshloop** [comment]
@mainawycliffe  https://deploy-preview-1232--goofy-euclid-75956c.netlify.app/catalog/018848bc-7889-90cb-03f3-b2c21766fa23 does not have a modal title
Screenshot 2023-09-12 at 11 51 47

**Comment by mainawycliffe** [comment]
@moshloop Ah, I see what the issue is. Let me fix it.

**Pull request merged**
